// src/domain/value-objects/academic.ts
// Academic datasets: Complete accredited list of Nigerian Universities & NUC Engineering Disciplines.

export const NIGERIAN_UNIVERSITIES: string[] = [
  'ABTI American University of Nigeria',
  'Abia State Polytechnic',
  'Abia State University',
  'Abubakar Tafawa Balewa University',
  'Adamawa State University',
  'Adekunle Ajasin University',
  'Adeleke University',
  'Adeyemi College of Education',
  'Afe Babalola University',
  'African University of Science and Technology',
  'Ahmadu Bello University',
  'Ajayi Crowther University',
  'Akanu Ibiam Federal Polytechnic, Unwana',
  'Akwa Ibom State University of Technology',
  'Al-hikmah University',
  'Ambrose Alli University',
  'Anambra State University of Science and Technology',
  'Auchi Polytechnic',
  'Babcock University',
  'Bauchi State University, Gadau',
  'Bayero University Kano',
  'Baze University Abuja',
  'Bells University of Technology',
  'Benson Idahosa University',
  'Benue State University',
  'Bingham University',
  'Bowen University',
  'Caleb University',
  'Caritas University',
  'College of Education Ikere',
  'College of Education Oju',
  'Covenant University',
  'Crawford University',
  'Crescent University',
  'Cross River University of Science and Technology',
  'Ebonyi State University',
  'Ekiti State University',
  'Enugu State University of Science and Technology',
  'Federal College Of Education (Technical), Akoka',
  'Federal University of Agriculture Abeokuta (FUNAAB)',
  'Federal University of Agriculture Makurdi',
  'Federal University of Petroleum Resources (FUPRE)',
  'Federal University of Technology, Akure (FUTA)',
  'Federal University of Technology, Minna (FUTMinna)',
  'Federal University of Technology, Owerri (FUTO)',
  'Federal University of Technology, Yola',
  'Fountain University',
  'Godfrey Okoye University',
  'Gombe State University',
  'Ibrahim Babangida University',
  'Igbinedion University',
  'Imo State University',
  'Institute of Management and Technology (IMT), Enugu',
  'Joseph Ayo Babalola University',
  'Kaduna Polytechnic',
  'Kaduna State University',
  'Kano State University of Technology Wudil',
  'Katsina University',
  'Kebbi State University of Science and Technology',
  'Kogi State University',
  'Kwara State Polytecnic',
  'Kwara State University',
  'Kwararafa University',
  'Ladoke Akintola University of Technology (LAUTECH)',
  'Lagos City Polytechnic',
  'Lagos State Polytechnic (LASPOTECH)',
  'Lagos State University (LASU)',
  'Landmark University',
  'Lead City University of Ibadan',
  'Madonna University',
  'Michael Okpara University of Agriculture',
  'Miva Open University',
  'Nasarawa State University Keffi',
  'National Open University of Nigeria (NOUN)',
  'Niger Delta University',
  'Nigerian Defence Academy (NDA)',
  'Nile University of Nigeria',
  'Nnamdi Azikiwe University (UNIZIK)',
  'Novena University',
  'Obafemi Awolowo University (OAU)',
  'Obong University',
  'Oduduwa University',
  'Olabisi Onabanjo University (OOU)',
  'Ondo State University of Science and Technology',
  'Osun State University (UNIOSUN)',
  'Pan-African University',
  'Pan-Atlantic University',
  'Paul University',
  'Polytechnic Ibadan',
  'Redeemers University',
  'Renaissance University',
  'Rivers State University',
  'Salem University',
  'Sokoto State University',
  'Tai Solarin University of Education',
  'Tansian University',
  'Taraba State University',
  'The Achievers University',
  'The Federal Polytechnic Offa',
  'Umaru Musa Yar\'Adua University',
  'University of Abuja (UNIABUJA)',
  'University of Benin (UNIBEN)',
  'University of Calabar (UNICAL)',
  'University of Ibadan (UI)',
  'University of Ilorin (UNILORIN)',
  'University of Jos (UNIJOS)',
  'University of Lagos (UNILAG)',
  'University of Maiduguri (UNIMAID)',
  'University of Mkar',
  'University of Nigeria, Nsukka (UNN)',
  'University of Port Harcourt (UNIPORT)',
  'University of Uyo (UNIUYO)',
  'Usmanu Danfodiyo University Sokoto',
  'Veritas University',
  'Wellspring University',
  'Wesley University of Science and Technology',
  'Western Delta University',
  'Yaba College of Technology (YABATECH)',
];

export function getNigerianUniversities(): string[] {
  return NIGERIAN_UNIVERSITIES;
}

// Backwards compatibility async fetcher (returns immediately without network lag)
export async function fetchNigerianUniversities(): Promise<string[]> {
  return NIGERIAN_UNIVERSITIES;
}

export const NUC_ENGINEERING_COURSES = [
  'Agricultural & Bio-Resources Engineering',
  'Aerospace Engineering',
  'Biomedical Engineering',
  'Chemical Engineering',
  'Civil Engineering',
  'Computer Engineering',
  'Electrical & Electronics Engineering',
  'Industrial & Production Engineering',
  'Marine & Naval Architecture Engineering',
  'Materials & Metallurgical Engineering',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Petroleum & Gas Engineering',
  'Software Engineering',
  'Structural Engineering',
  'Systems Engineering',
  'Other / Discipline Not Listed',
] as const;

export type NucEngineeringCourse = (typeof NUC_ENGINEERING_COURSES)[number];
